board: None
name: Default (Test Drive)
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0

axes:
  shared_stepper_disable: NO_PIN
  x:
    steps_per_mm: 320.000
    max_rate: 1000.000
    acceleration: 25.000
    max_travel: 200.000
    soft_limits: false

  y:
    steps_per_mm: 320.000
    max_rate: 1000.000
    acceleration: 25.000
    max_travel: 200.000
    soft_limits: false

  z:
    steps_per_mm: 320.000
    max_rate: 1000.000
    acceleration: 25.000
    max_travel: 200.000
    soft_limits: false

spi:
  miso: NO_PIN
  mosi: NO_PIN
  sck: NO_PIN

control:
  safety_door: NO_PIN
  reset: NO_PIN
  feed_hold: NO_PIN
  cycle_start: NO_PIN
  macro0: NO_PIN
  macro1: NO_PIN
  macro2: NO_PIN
  macro3: NO_PIN

coolant:
  flood: NO_PIN
  mist: NO_PIN
  delay_ms: 0

probe:
  pin: NO_PIN
  check_mode_start: true

macros:
  n0:
  n1:
  macro0:
  macro1:
  macro2:
  macro3:

user_outputs:
  analog0: NO_PIN
  analog1: NO_PIN
  analog2: NO_PIN
  analog3: NO_PIN
  analog_frequency0: 5000
  analog_frequency1: 5000
  analog_frequency2: 5000
  analog_frequency3: 5000
  digital0: NO_PIN
  digital1: NO_PIN
  digital2: NO_PIN
  digital3: NO_PIN

sdcard:
  card_detect: NO_PIN
  cs: gpio.5

software_debounce_ms: 0
laser_mode: false
arc_tolerance: 0.002
junction_deviation: 0.010
verbose_errors: false
report_inches: false
homing_init_lock: true
enable_parking_override_control: false
deactivate_parking_upon_init: false
check_limits_at_init: true
limits_two_switches_on_axis: false
disable_laser_during_hold: true
use_line_numbers: false
NoSpindle:
